USE LIBRARY
SELECT BOOK.NAME_BOOK, AUTHOR.NAME
FROM BOOK 
inner join AUTHOR ON BOOK.NAME_AUTHOR = AUTHOR.NAME
WHERE BOOK.YEAR_OF_RELEASE = 2002 OR BOOK.YEAR_OF_RELEASE = 2001

USE LIBRARY
SELECT AUTHOR.NAME, AUTHOR.COUNTRY, BOOK.NAME_BOOK
FROM BOOK
inner join AUTHOR ON BOOK.NAME_AUTHOR = AUTHOR.NAME
GROUP BY AUTHOR.NAME, AUTHOR.COUNTRY, BOOK.NAME_BOOK

USE LIBRARY
SELECT AUTHOR.NAME, AUTHOR.COUNTRY, count(BOOK.NAME_BOOK)[COUNT_BOOK]
FROM BOOK
inner join AUTHOR ON BOOK.NAME_AUTHOR = AUTHOR.NAME
GROUP BY AUTHOR.NAME, AUTHOR.COUNTRY
HAVING count(BOOK.NAME_BOOK) > 1

SELECT *
FROM BOOK

DELETE FROM BOOK
WHERE YEAR_OF_RELEASE > 2008